packaging_format = 2

id = "focalboard"
name = "Focalboard"
description.en = "Kanban project management software"
description.fr = "Logiciel de gestion de projet Kanban"

version = "7.11.4~ynh2"

maintainers = []

[upstream]
license = "MIT"
website = "https://www.focalboard.com/"
admindoc = "https://www.focalboard.com/guide/admin/"
userdoc = "https://www.focalboard.com/guide/user/"
code = "https://github.com/mattermost/focalboard"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = ["amd64"]
multi_instance = false

ldap =  false

sso = false

disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/mattermost/focalboard/releases/download/v7.11.3/focalboard-server-linux-amd64.tar.gz"
        sha256 = "3515ef5b90fe2d958b8869e0191915f0ca46ee4e6950e16c9647423981ebeecd"
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "^focalboard-server-linux-amd64.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.show_tile = false
    api.allowed = "visitors"
    api.auth_header = false

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
