packaging_format = 2

id = "focalboard"
name = "Focalboard"
description.en = "Kanban project management software"
description.fr = "Logiciel de gestion de projet Kanban"

version = "7.11.4~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "https://www.focalboard.com/"
admindoc = "https://www.focalboard.com/guide/admin/"
userdoc = "https://www.focalboard.com/guide/user/"
code = "https://github.com/mattermost/focalboard"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64"]
multi_instance = false

ldap =  false

sso = false

disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/mattermost/focalboard/archive/refs/tags/v7.11.4.tar.gz"
        sha256 = "46bdcb95b2b26b38bc7b65465d2aade77721c2f861d72b4e8abd9de80ddf0082"
        autoupdate.strategy = "latest_github_release"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.show_tile = false
    api.allowed = "visitors"
    api.auth_header = false

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
